### ISSUE TITLE
Unable do quick download a whole MediaCorp Collection series.

### ISSUE THREAD

**Issue by cmemil** [0x776b7364/toggle.sg-download#12]
I cannot quickly batch download the whole series of a number of MediaCorp Collection series such as:

http://video.toggle.sg/en/series/the-winning-team/ep25/366497
http://video.toggle.sg/en/series/katong-miss-oh-miss-oh/ep13/362186
http://video.toggle.sg/en/series/lobang-king-lobang-king/ep22/3622

In order to download the entire series, I need to copy each episode link one by one and manually paste in cmd which can take up a lot of time. Is there any way to have a whole series link?

**Comment by 0x776b7364** [comment]
Did you use the latest script, the one with the series support?

**Comment by cmemil** [comment]
Yes, I did, but it asks me to select the quality (STB/iPad/IPH/ADD) for every single one of the files, even though the order of those are exactly the same and STB (my preferred option) is always number 3 every time for all 25 episodes. Just wondering if there's any way to permanantly select STB instead of entering "3" every time?

Also, after a few seconds of downloading an m3u8 video, I get the following:

```
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
[!] Error: ffmpeg file not found, or existing file is for incorrect architecture
[i] Thread 20d8cbfd completed download!
[i] Done!
```
I've tried using the latest version of ffmpeg.exe and placed it in the same folder as `download_toggle_video2.py`
I've tried using the same ffmpeg.exe file for converting a few videos which worked.

**Comment by 0x776b7364** [comment]
I've just updated the README. See if you can set the AUTO_DOWNLOAD option to 1. FILE_PREFERENCES already sets STB as the first (and highest priority), and so that should suit you. Do provide the Toggle episode URL so that I can replicate the m3u8 download issue.

**Comment by cmemil** [comment]
Thanks for that. It now allows me to batch download an entire series with no interaction. However, the ffmpeg issue remains.

**Comment by gromgit** [comment]
@cmemil Your ffmpeg m3u8 issue is almost certainly the one I reported yesterday: #13

**Comment by 0x776b7364** [comment]
I'll close this as the file format selection issue is resolved. We can take up the ffmpeg issue on the other thread.
